#! perl

use v5.20;
use strict;
use warnings;

my $ctrl_mask = 4;
my $pid;

sub on_child_start {
    $pid = $_[1];
}

sub on_key_release {
    my %event = %{ $_[1] };
    my $keysym = $_[2];
    my $ctrl_pressed = $event{"state"} & $ctrl_mask;

    my $cwd = readlink "/proc/$pid/cwd";

    if ($ctrl_pressed and ord "n" == $keysym) {
        `urxvt -cd "$cwd" & disown`
    }

    1;
}
