#! perl

use v5.20;
use strict;
use warnings;

# shift => 1, ctrl => 4, alt => 8
my $trigger_mod_mask = 12;
my $trigger_key = "n";
my $pid;

sub on_child_start {
    $pid = $_[1];
}

sub trigger {
    my ($state, $keysym) = @_;
    my $mod_pressed = ($state & $trigger_mod_mask) == $trigger_mod_mask;
    return $mod_pressed && ord $trigger_key == $keysym;
}

sub on_key_press {
    my %event = %{ $_[1] };
    my $keysym = $_[2];

    return trigger($event{"state"}, $keysym);
}

sub on_key_release {
    my %event = %{ $_[1] };
    my $keysym = $_[2];

    my $triggered = trigger($event{"state"}, $keysym);
    if ($triggered) {
        my $cwd = readlink "/proc/$pid/cwd";

        `urxvt -cd "$cwd" & disown` if -d $cwd
    }
    return $triggered;
}
